version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gutendex
      POSTGRES_USER: gutendex
      POSTGRES_PASSWORD: gutendex
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - /home/neilg/Documents/Bootcamp/exam-1-gutendex/project_v2/gutendex/catalog_files/rdf:/app/catalog_files
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
